AppBundle\Entity\Customer:
    type: entity
    repositoryClass: AppBundle\Repository\CustomerRepository
    table: customer
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        ref:
            type: string
            nullable: false
            length: 45
            fixed: false
        name:
            type: string
            nullable: false
            length: 45
            fixed: false
        address:
            type: string
            nullable: false
            length: 45
            fixed: false
        postalcode:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: postalCode
        city:
            type: string
            nullable: false
            length: 45
            fixed: false
        telephone:
            type: string
            nullable: true
            length: 45
            fixed: false
        email:
            type: string
            nullable: false
            length: 45
            fixed: false
    oneToMany:
        order:
          targetEntity: Order
          mappedBy: category
