AppBundle\Entity\Delivery:
    type: entity
    repositoryClass: AppBundle\Repository\DeliveryRepository
    table: delivery
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        ref:
            type: string
            nullable: false
            length: 45
            fixed: false
        datedelivery:
            type: date
            nullable: false
            column: dateDelivery
    manyToOne:
        invoice:
            targetEntity: Invoice
            inversedBy: delivery
            joinColumn:
              name: invoiceId
              referencedColumnName: id
        order:
            targetEntity: Order
            inversedBy: delivery
            joinColumn:
              name: orderId
              referencedColumnName: id
