AppBundle\Entity\Invoice:
    type: entity
    repositoryClass: AppBundle\Repository\InvoiceRepository
    table: invoice
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        ref:
            type: string
            nullable: false
            length: 45
            fixed: false
        dateinvoice:
            type: date
            nullable: false
            column: dateInvoice
    oneToMany:
        delivery:
          targetEntity: Delivery
          mappedBy: category
