AppBundle\Entity\OrderDetail:
    type: entity
    repositoryClass: AppBundle\Repository\OrderDetailRepository
    table: orderDetail
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        qte:
            type: float
            nullable: false
            precision: 10
            scale: 0
    manyToOne:
        order:
            targetEntity: Order
            inversedBy: orderDetail
            joinColumn:
              name: orderId
              referencedColumnName: id
        product:
            targetEntity: Product
            inversedBy: orderDetail
            joinColumn:
              name: productId
              referencedColumnName: id
